### ISSUE TITLE
Gnome 43 Nautilus update?

### ISSUE THREAD

**Issue by vescovaccio** [costales/yaru-colors-folder-color#2]
I just upgraded from Ubuntu 22.04 to 22.10, running Gnome 43. Sadly there are no longer any Folder Colors options in Nautilus 43's right click context menu. So, while I have the folders already coloured, I have no way of changing their colours. Are you planning to update the folder colors code for the latest version of Nautilus (GKT4)?

I have used Folder Colors for years - thank you so much! Hope it will be updated!

**Comment by costales** [comment]
Hi!

Yes, I tried without luck. I'll try it again soon.

Related to: https://github.com/costales/folder-color/issues/17

Thank you for the feedback!
