### ISSUE TITLE
Compatibility with Ubuntu 24.04?

### ISSUE THREAD

**Issue by vescovaccio** [costales/yaru-colors-folder-color#4]
Unbelievably or not, yaru-colors-folder-color is the only thing that makes me hesitant about updating from Ubuntu 22.04 LTS to the current Ubuntu 24.04 LTS. If I update, will it continue to work? And if I wipe 22.04 to install 24.04, will I be able to install yaru-colors-folder-color again? So much have I come to rely on Folder Colors. Many thanks for Folder Colors all of these years - here's hoping it will work in 22.04 too!

**Comment by costales** [comment]
Hi, I can't asure you that, could you test in a virtual machine or in a Live USB? :) https://launchpad.net/~costales/+archive/ubuntu/folder-color?field.series_filter=noble

The unique package from now is `folder-color` and it includes the Yaru icons ;)

Best regards.

PS: If you test 24.04, could you give us feedback? Thanks!

**Comment by vescovaccio** [comment]
Thanks! Yes, I'll test and let you know. Fingers crossed!
